// src/pages/lists/[slug].tsx
import initPocketBase from "@/helpers/initPocketbase";
import type {GetServerSidePropsContext} from "next";
import Head from "next/head";
import Link from "next/link";
import {Record} from "pocketbase";
import {useState} from "react";
import {IconSend} from "@tabler/icons-react";
import SuccessAlert from "@/components/alerts/success";
import WarningAlert from "@/components/alerts/warning";
import InfoAlert from "@/components/alerts/info";
import ErrorAlert from "@/components/alerts/error";

type RegionObject = {
    id: string;
    label: string;
}

type ListObject = {
    id: string;
    name: string;
    slug: string;
    regions: [RegionObject];
}

export default function ListView({list}: { list: ListObject }) {

    const [selectedRegion, setRegion] = useState(list.regions[0].id);
    const [isSuccess, setSuccess] = useState(false);
    const [isError, setError] = useState(false);
    const [isWarning, setWarning] = useState({active: false, text: ''});
    const [isDuplicate, setDuplicate] = useState(false);

    const handleSubmit = async (event: any) => {

        event.preventDefault();
        // reset states
        setSuccess(false);
        setError(false);
        setDuplicate(false);
        setWarning({active: false, text: ''})

        try {
            const data = JSON.stringify({
                email: event.target.email.value,
                region: selectedRegion,
                list: list.id
            });

            const options = {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: data,
            }

            const response = await fetch('/api/entries/add', options);
            if (response.status == 201) {
                setSuccess(true);
            } else if (response.status == 400) {
                const text = (await response.json()).text
                setWarning({active: true, text: text});
            } else if (response.status == 409) {
                setDuplicate(true);
            } else if (response.status >= 500) {
                setError(true);
            }
        } catch (e) {
            console.log(e);
        }
    }

    return (
        <>
            <Head>
                <title>{`Lyst - ${list.name}`}</title>
            </Head>

            <div>
                {
                    isSuccess && <SuccessAlert text={`Your mail address has been added to the waitinglist!`}/>
                }
                {
                    isWarning.active && <WarningAlert text={isWarning.text}/>
                }
                {
                    isDuplicate && <InfoAlert text={`The entered mail address has been added to the list already.`}/>
                }
                {
                    isError && <ErrorAlert
                        text={`There has been an unhandled error. Please contact the admin: alex@tailbyte.org`}/>
                }
                <form onSubmit={handleSubmit}>
                    <div className="form-control max-w-md mx-auto">
                        <h1 className="text-3xl my-4">{list.name}</h1>

                        <div className="form-control my-2">
                            <label className="label" htmlFor="email">
                                <span className="label-text">Your email address</span>
                            </label>
                            <input
                                type="email"
                                placeholder="awesome@aottr.dev"
                                name="email"
                                className="input input-bordered border-primary"
                            />
                        </div>
                        <div className="form-control my-2">
                            <label className="label">
                                <span className="label-text">Your preferred warehouse region</span>
                            </label>
                            <div className="btn-group btn-group-vertical">
                                {list.regions.map((region: RegionObject) => (
                                    <span className={`btn ${selectedRegion == region.id ? 'btn-active' : ''}`}
                                          key={region.id} onClick={() => {
                                        setRegion(region.id)
                                    }}>
                                    {region.label}
                                </span>
                                ))}
                            </div>
                        </div>
                        <button type="submit" className="btn btn-success my-2">
                            Put me on the list ! <IconSend className="ml-2"/>
                        </button>
                    </div>
                </form>
                <Link href="/" className="btn mt-10">Back</Link>
            </div>
        </>
    )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
    const pb = await initPocketBase(context);
    const {slug} = context.query
    try {
        const list = await pb.collection('waitinglists').getFirstListItem(`slug="${slug}"`, {
            expand: 'regions'
        })
        const ret = list ? {
            id: list.id,
            name: list.name,
            slug: list.slug,
            regions: list.expand.regions.map((record: Record) => {
                return {id: record.id, label: record.label}
            }),

        } as ListObject : null

        return {
            props: {
                list: ret
            }
        }
    } catch (error) {
        const {res} = context
        res.writeHead(301, {Location: '/'})
        res.end()
        return true
    }
}

// pages/lists/[slug].vue
<script setup lang="ts">
interface OptionsState {
  region: string;
}

const route = useRoute();
const slug = route.params.slug;

const lists = (await $fetch('/api/waitinglists')).data;
const regions = (await $fetch('/api/regions')).data;
console.log(regions);
const list = lists.find((list) => list.slug == slug);
if (!list) clearError({ redirect: '/' });
const email = ref('');
const success = ref(false);
const options = reactive<OptionsState>({
  region: regions[0].id || '',
});

const handleSubmit = async () => {
  const formatedEmail = email.value.trim();
  email.value = '';

  if (!formatedEmail) return;
  const entry = await $fetch('/api/entry', {
    method: 'POST',
    body: JSON.stringify({
      email: formatedEmail,
      waitinglist: list?.id,
      region: list?.regions2.length ? options.region : null,
    }),
  });
  success.value = true;
};
</script>

<template>
  <Html>
    <Head>
      <Title v-if="list">{{ list.name }}</Title>
    </Head>
  </Html>
  <div v-if="list">
    <div v-if="success" class="alert alert-success shadow-lg my-3">
      <div>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="stroke-current flex-shrink-0 h-6 w-6"
          fill="none"
          viewBox="0 0 24 24">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Your mail address has been added to the waitinglist !</span>
      </div>
    </div>

    <div class="form-control max-w-md mx-auto">
      <h1 class="text-3xl my-4">{{ list.name }}</h1>
      <div class="form-control my-2">
        <label class="label">
          <span class="label-text">Your email address</span>
        </label>
        <input
          v-model="email"
          type="email"
          placeholder="awesome@aottr.dev"
          class="input input-bordered"
          minlength="6"
          required />
      </div>
      <div class="form-control my-2" v-if="list.regions.length">
        <label class="label">
          <span class="label-text">Your preferred warehouse region</span>
        </label>
        <div class="btn-group btn-group-vertical">
          <button
            v-for="region in regions"
            class="btn"
            :class="options.region === region.id && 'btn-active'"
            @click="options.region = region.id">
            {{ region.label }}
          </button>
        </div>
      </div>
      <button v-on:click="handleSubmit" class="btn btn-success my-2">
        Put me on the list !
      </button>
    </div>
    <NuxtLink to="/" class="btn mt-10">Back</NuxtLink>
  </div>
</template>
